version: "3.8"
services:
  client:
    build: ./client
    depends_on:
      - server
    container_name: algo-viz-client
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  server:
    build: ./server
    container_name: algo-viz-server
    ports:
      - '3001:3001'
