# Your workflow name.
name: Deploy to Heroku.

# Run workflow on every push to main branch.
on:
  push:
    branches: [production]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

### ⬇ IMPORTANT PART ⬇ ###
      - name: Build, Push, and Release Client Docker Container
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_CLIENT_APP }}
          # (Optional, default: "./")
          dockerfile_directory: ./client
          dockerfile_name: Dockerfile.web
          # (Optional, default: "")
          docker_options: "--no-cache"
          # (Optional, default: "web")
          process_type: web
      - name: Build, Push, and Release Server Docker Container
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_SERVER_APP }}
          # (Optional, default: "./")
          dockerfile_directory: ./server
          dockerfile_name: Dockerfile.web
          # (Optional, default: "")
          docker_options: "--no-cache"
          # (Optional, default: "web")
          process_type: web

### ⬆ IMPORTANT PART ⬆ ###
